remote_theme: pages-themes/minimal@v0.2.0
owner: chiral
plugins:
- jekyll-remote-theme
- jekyll-tabs
logo: /assets/img/logo.png
description: 
  - An Open-Source Tool for High-Performance Data Processing and Visualization written in Rust
# <script src="https://asciinema.org/a/14.js" id="asciicast-14" async data-autoplay="true" data-size="big" data-speed="30" data-loop="true"></script>
