remote_theme: pages-themes/minimal@v0.2.0
owner: chiral
plugins:
- jekyll-remote-theme
- jekyll-tabs
logo: /assets/img/logo.png
description: An Open-Source Tool for High-Performance Data Processing and Visualization written in Rust
url: https://www.chiral.one

title: chiral
repository: chiral-data/chiral-data.github.io 
